name: patatudo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  equatable: ^2.0.5
  cached_network_image: ^3.4.0
  camera: ^0.11.0
  cloud_firestore: ^5.2.1
  cloud_functions: ^5.0.4
  firebase_analytics: ^11.2.1
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_database: ^11.0.4
  firebase_messaging: ^15.0.4
  firebase_storage: ^12.1.3
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^17.2.2
  flutter_modular: ^6.3.4
  flutter_secure_storage: ^9.2.4
  # Not change version for font_awesome_flutter
  font_awesome_flutter: '>= 4.7.0'
  gap: ^3.0.1
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  intl: ^0.19.0
  stack_trace: ^1.11.1
  uuid: ^4.5.0

dependency_overrides:
  font_awesome_flutter:
    path: ../font_awesome_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
